name: Build and Push Docker Images to Docker Hub
on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Build and push the wsrc-app image
      - name: Build and push wsrc-app
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wsrc:app -f ./wsrc-app/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wsrc:app

      # # Step 4: Build and push the wsrc-api image
      # - name: Build and push wsrc-api
      #   run: |
      #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wsrc-api:dev -f ./wsrc-api/Dockerfile.dev .
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/wsrc-api:dev
